name: Build Extension
permissions:
  id-token: write # Required for requesting the JWT
  contents: read

on:
  workflow_dispatch:
    inputs:
      bs_os_version:
        required: true
        type: choice
        description: "Brightsign OS Version"
        options:
          - 9.1.52

      build-models:
        description: "Build models"
        required: true
        type: boolean
        default: false

      build-sdk:
        description: "Build SDK"
        required: true
        type: boolean
        default: false

env:
  DOCKER_IMAGE: bsoe-build
  S3_URL: s3://bs-npu-artifacts-cicd/brightsign-npu-yolox

jobs:
  build-extension:
    runs-on: ubuntu-latest-4-cores
    steps:
      - name: checkout code
        uses: actions/checkout@v4     

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::207998159418:role/github-actions-npu-repos-role
          aws-region: us-east-1      

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Environment variables
        run: |
          echo "BRIGHTSIGN_OS_VERSION=${{ inputs.bs_os_version }}" >> "$GITHUB_ENV"

      - name: Check if Docker image exists
        id: check-image
        run: |
          cmd="$(aws ecr describe-images --repository-name ${{ env.DOCKER_IMAGE }} --image-ids imageTag=${{ inputs.bs_os_version }} ||:)"
          if [[ -z "$cmd" ]]; then
            echo "IMAGE_EXISTS=false" >> "$GITHUB_ENV"
          else
            echo "IMAGE_EXISTS=true" >> "$GITHUB_ENV"
          fi

      - name: Run setup command without build
        run: |
          ./setup -y --without-build --version ${{ inputs.bs_os_version }}

      - name: Get Docker image
        if: ${{ env.IMAGE_EXISTS == 'true' }}
        run: |
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.DOCKER_IMAGE }}:${{ env.BRIGHTSIGN_OS_VERSION }}
          mkdir -p srv
          chmod 777 srv

      - name: Set up Docker Buildx
        if: ${{ env.IMAGE_EXISTS == 'false' }}
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        if: ${{ env.IMAGE_EXISTS == 'false' }}
        id: dockerbuild
        uses: docker/build-push-action@v6
        with:
          build-args: |
              BRIGHTSIGN_OS_VERSION=${{ env.BRIGHTSIGN_OS_VERSION }}
          file: ./Dockerfile
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.DOCKER_IMAGE }}:${{ env.BRIGHTSIGN_OS_VERSION }}
          load: true
          push: true      

      - name: Tag Docker image
        run: |
          docker tag ${{ steps.login-ecr.outputs.registry }}/${{ env.DOCKER_IMAGE }}:${{ env.BRIGHTSIGN_OS_VERSION }} ${{ env.DOCKER_IMAGE }}

      - name: Compile models
        if: ${{ inputs.build-models == true }}
        run: |
          ./compile-models -q
          tar -czf install-models.tgz install
          aws s3 cp install-models.tgz ${{ env.S3_URL }}/models/install-models.tgz

      - name: Download models
        if: ${{ inputs.build-models == false }}
        run: |
          aws s3 ls ${{ env.S3_URL }}/models/install-models.tgz && aws s3 cp ${{ env.S3_URL }}/models/install-models.tgz . &&  tar -xzf install-models.tgz || ./compile-models && tar -czf install-models.tgz install && aws s3 cp install-models.tgz ${{ env.S3_URL }}/models/install-models.tgz

      - name: Compile SDK
        if: ${{ inputs.build-sdk == true }}
        run: |
          ./build --extract-sdk
          aws s3 cp ./brightsign-x86_64-cobra-toolchain-${{ env.BRIGHTSIGN_OS_VERSION }}.sh ${{ env.S3_URL }}/sdk/

      - name: Get SDK
        if: ${{ inputs.build-sdk == false }}
        run: |
          aws s3 ls ${{ env.S3_URL }}/sdk/brightsign-x86_64-cobra-toolchain-${{ env.BRIGHTSIGN_OS_VERSION }}.sh && aws s3 cp ${{ env.S3_URL }}/sdk/brightsign-x86_64-cobra-toolchain-${{ env.BRIGHTSIGN_OS_VERSION }}.sh . || ./build --extract-sdk && aws s3 cp ./brightsign-x86_64-cobra-toolchain-${{ env.BRIGHTSIGN_OS_VERSION }}.sh ${{ env.S3_URL }}/sdk/ 

      - name: Build apps
        run: |
          ./build-apps

      - name: Package extension
        run: |
          ./package

      - name: Export dev packages
        run: |
          aws s3 cp ./yolo-dev-*.zip ${{ env.S3_URL }}/packages/development/
          aws s3 cp ./yolo-ext-*.zip ${{ env.S3_URL }}/packages/extension/
